// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSUO75_Y8CvJtmi2Fqh_EyGeWBOqQV2gk',
    appId: '1:236712331640:android:e086f8ca84a967849c208d',
    messagingSenderId: '236712331640',
    projectId: 'test-1b77a',
    storageBucket: 'test-1b77a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIkDHCPzly7nAjjOa-UpcQE4yAVOAWH8I',
    appId: '1:236712331640:ios:99f7b8c4be384f7e9c208d',
    messagingSenderId: '236712331640',
    projectId: 'test-1b77a',
    storageBucket: 'test-1b77a.firebasestorage.app',
    androidClientId: '236712331640-lob4e4t7g51pso0qsmudu1c5ku90sa1r.apps.googleusercontent.com',
    iosClientId: '236712331640-vuee2jhds7n9jpqhqi8of29ht5pfergd.apps.googleusercontent.com',
    iosBundleId: 'com.example.breadcrumbs',
  );
}
